function validationPixelLabelIdMappingList = importValidationPixelLabelMappingList(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VALIDATIONPIXELLABELIDMAPPINGLIST = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  VALIDATIONPIXELLABELIDMAPPINGLIST = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  validationPixelLabelIdMappingList = importfile("D:\Dokumente\HS Esslingen\01_Master\03_Forschungsprojekt\ImageProcessingScripts\labeling\validationPixelLabelIdMappingList.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-May-2021 14:08:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["name", "invalidPixelLabelID", "validPixelLabelID"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "name", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "name", "EmptyFieldRule", "auto");

% Import the data
validationPixelLabelIdMappingList = readtable(filename, opts);

end